---
- hosts: all
  remote_user: vagrant
  sudo: yes
  roles:
    - mivok0.users
    - angstwad.docker_ubuntu
  tasks:
    - name: ensure ntpd is at the latest version
      apt: pkg=ntp state=latest
      notify:
      - restart ntpd
    - name: launch docker sshd
      docker: image=smo921/ubuntu-ssh port_bindings=22:40022
    - name: Display IP address and port mappings for containers
      debug: msg={{inventory_hostname}} {{item.NetworkSettings}}
      with_items: docker_containers

  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted

