---
- hosts: all
  remote_user: vagrant
  sudo: yes
  roles:
    - mivok0.users
    - angstwad.docker_ubuntu
  tasks:
    - name: launch docker mysqld
      docker: image=tutum/mysql ports=3306:3306
    - name: Display IP address and port mappings for all containers
      debug: msg={{inventory_hostname}} {{item.NetworkSettings}}
      with_items: docker_containers
